version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: userApiDB
      MYSQL_USER: canwia
      MYSQL_PASSWORD: canwia
      MYSQL_ROOT_PASSWORD: canwia
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: canwia
      RABBITMQ_DEFAULT_PASS: canwia
    ports:
      - "5672:5672"   # RabbitMQ message broker
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  rabbitmq_data:
